sudo: false
language: node_js
node_js:
  - 12
  - '10'
  - '8'

before_script:
  - 'git config --global user.email "you@example.com"'
  - 'git config --global user.name "Your Name"'

after_script: 'cat ./coverage/lcov.info | coveralls'